/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tebak_Kata;

import Menu.credit;
import DBKon.koneksi;
import java.sql.SQLException;
import java.awt.event.KeyEvent;
import java.sql.Statement;
import javax.swing.JOptionPane;


/**
 *
 * @author USER
 */
public class MainMenu extends javax.swing.JFrame {
koneksi kon;
int skor = 0;
    /**
     * Creates new form MainMenu
     */
    public static String username;
  
    public MainMenu() {
        initComponents();
        kon = new koneksi();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JLabel();
        jBack1 = new javax.swing.JLabel();
        jBack2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldUsername.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        jTextFieldUsername.setForeground(new java.awt.Color(150, 70, 0));
        jTextFieldUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldUsername.setBorder(null);
        jTextFieldUsername.setSelectionColor(new java.awt.Color(255, 204, 0));
        jTextFieldUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldUsernameKeyPressed(evt);
            }
        });
        jPanel1.add(jTextFieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 330, 50));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(150, 70, 0));
        jLabel3.setText("START");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 398, 120, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tebak_Kata/img/button1.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 391, 42, 42));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tebak_Kata/img/button2.png"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 391, 42, 42));

        jBack1.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        jBack1.setForeground(new java.awt.Color(204, 51, 0));
        jBack1.setText("Back");
        jBack1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBack1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBack1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBack1MouseExited(evt);
            }
        });
        jPanel1.add(jBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 80, 40));

        jBack2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        jBack2.setText("Back");
        jBack2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBack2MouseClicked(evt);
            }
        });
        jPanel1.add(jBack2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 80, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tebak_Kata/img/Main menu.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldUsernameKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            username = jTextFieldUsername.getText();
            try{
                String tambah = "insert into tebak_kata (user, skor) values ('"+username+"','"+skor+"')";
                Statement st = kon.con.createStatement();
                st.executeUpdate(tambah);
            } catch (Exception e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
            this.setVisible(false);
            new AturanMain().setVisible(true);
        }
    }//GEN-LAST:event_jTextFieldUsernameKeyPressed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        username = jTextFieldUsername.getText();
        try{
            String tambah = "insert into tebak_kata(user, skor) values ('"+username+"','"+skor+"')";
            Statement st = kon.con.createStatement();
            st.executeUpdate(tambah);
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        this.setVisible(false);
        new AturanMain().setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        jButton1.setVisible(false);
        jButton2.setVisible(true);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        jButton1.setVisible(true);
        jButton2.setVisible(false);
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        username = jTextFieldUsername.getText();
        try{
            String tambah = "insert into tebak_kata (user, skor) values ('"+username+"','"+skor+"')";
            Statement st = kon.con.createStatement();
            st.executeUpdate(tambah);
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        this.setVisible(false);
        new AturanMain().setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jBack1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBack1MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Menu.MainMenu().setVisible(true);
    }//GEN-LAST:event_jBack1MouseClicked

    private void jBack1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBack1MouseEntered
        // TODO add your handling code here:
        jBack1.setVisible(false);
        jBack2.setVisible(true);
    }//GEN-LAST:event_jBack1MouseEntered

    private void jBack1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBack1MouseExited
        // TODO add your handling code here:
        jBack1.setVisible(true);
        jBack2.setVisible(false);
    }//GEN-LAST:event_jBack1MouseExited

    private void jBack2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBack2MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Menu.MainMenu().setVisible(true);
    }//GEN-LAST:event_jBack2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jBack1;
    private javax.swing.JLabel jBack2;
    private javax.swing.JLabel jButton1;
    private javax.swing.JLabel jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
}
