/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tebak_Kata;

import DBKon.koneksi;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author USER
 */
public class Success_Stage extends javax.swing.JFrame {
koneksi kon;
int skor = 0;
static String username = Tebak_Kata.MainMenu.username;
    /**
     * Creates new form Success
     */
    public Success_Stage(int skor) {
        initComponents();
        kon = new koneksi();
        this.skor = skor;
        jSelamat.setText(getUser());
        jSkor.setText(""+skor);
        try{
            String ubah = "update tebak_kata set skor = '"+skor+"' where user = '"+getUser()+"'";
            Statement st = kon.con.createStatement();
            st.executeUpdate(ubah);
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }    
    }
      
    public static String getUser(){
        String temp2 = Tebak_Kata.MainMenu.username;
        username = "";
        return temp2;   
    }
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSelamat = new javax.swing.JLabel();
        jExit1 = new javax.swing.JLabel();
        jExit2 = new javax.swing.JLabel();
        jPlayAgain1 = new javax.swing.JLabel();
        jPlayAgain2 = new javax.swing.JLabel();
        jSkor = new javax.swing.JLabel();
        jScore1 = new javax.swing.JLabel();
        jScore2 = new javax.swing.JLabel();
        jLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSelamat.setFont(new java.awt.Font("Matura MT Script Capitals", 1, 36)); // NOI18N
        jSelamat.setForeground(new java.awt.Color(7, 3, 3));
        jSelamat.setMaximumSize(new java.awt.Dimension(450, 50));
        jPanel1.add(jSelamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 220, 40));

        jExit1.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        jExit1.setForeground(new java.awt.Color(255, 204, 0));
        jExit1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jExit1.setText("Exit");
        jExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jExit1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jExit1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jExit1MouseExited(evt);
            }
        });
        jPanel1.add(jExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 490, 170, 50));

        jExit2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        jExit2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jExit2.setText("Exit");
        jExit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jExit2MouseClicked(evt);
            }
        });
        jPanel1.add(jExit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 490, 170, 50));

        jPlayAgain1.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        jPlayAgain1.setForeground(new java.awt.Color(255, 204, 0));
        jPlayAgain1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPlayAgain1.setText("Play Again");
        jPlayAgain1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPlayAgain1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPlayAgain1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPlayAgain1MouseExited(evt);
            }
        });
        jPanel1.add(jPlayAgain1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 166, 50));

        jPlayAgain2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        jPlayAgain2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPlayAgain2.setText("Play Again");
        jPlayAgain2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPlayAgain2MouseClicked(evt);
            }
        });
        jPanel1.add(jPlayAgain2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 166, 50));

        jSkor.setFont(new java.awt.Font("Matura MT Script Capitals", 1, 36)); // NOI18N
        jPanel1.add(jSkor, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 90, 40));

        jScore1.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        jScore1.setForeground(new java.awt.Color(255, 204, 0));
        jScore1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jScore1.setText("All Score");
        jScore1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScore1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jScore1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jScore1MouseExited(evt);
            }
        });
        jPanel1.add(jScore1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 490, 170, 50));

        jScore2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        jScore2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jScore2.setText("All Score");
        jScore2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScore2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jScore2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jScore2MouseExited(evt);
            }
        });
        jPanel1.add(jScore2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 490, 170, 50));

        jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tebak_Kata/img/Congrat Tebak Gambar.png"))); // NOI18N
        jPanel1.add(jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPlayAgain1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPlayAgain1MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_jPlayAgain1MouseClicked

    private void jPlayAgain2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPlayAgain2MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_jPlayAgain2MouseClicked

    private void jPlayAgain1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPlayAgain1MouseEntered
        // TODO add your handling code here:
        jPlayAgain1.setVisible(false);
        jPlayAgain2.setVisible(true);
    }//GEN-LAST:event_jPlayAgain1MouseEntered

    private void jPlayAgain1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPlayAgain1MouseExited
        // TODO add your handling code here:
        jPlayAgain1.setVisible(true);
        jPlayAgain2.setVisible(false);
    }//GEN-LAST:event_jPlayAgain1MouseExited

    private void jExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExit1MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Menu.MainMenu().setVisible(true);
    }//GEN-LAST:event_jExit1MouseClicked

    private void jExit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExit2MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Menu.MainMenu().setVisible(true);
    }//GEN-LAST:event_jExit2MouseClicked

    private void jExit1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExit1MouseEntered
        // TODO add your handling code here:
        jExit1.setVisible(false);
        jExit2.setVisible(true);
    }//GEN-LAST:event_jExit1MouseEntered

    private void jExit1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExit1MouseExited
        // TODO add your handling code here:
        jExit1.setVisible(true);
        jExit2.setVisible(false);
    }//GEN-LAST:event_jExit1MouseExited

    private void jScore1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScore1MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Peringkat(skor).setVisible(true);
    }//GEN-LAST:event_jScore1MouseClicked

    private void jScore2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScore2MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Peringkat(skor).setVisible(true);
    }//GEN-LAST:event_jScore2MouseClicked

    private void jScore2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScore2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jScore2MouseEntered

    private void jScore2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScore2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jScore2MouseExited

    private void jScore1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScore1MouseEntered
        // TODO add your handling code here:
        jScore1.setVisible(false);
        jScore2.setVisible(true);
    }//GEN-LAST:event_jScore1MouseEntered

    private void jScore1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScore1MouseExited
        // TODO add your handling code here:
        jScore1.setVisible(true);
        jScore2.setVisible(false);
    }//GEN-LAST:event_jScore1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Success_Stage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Success_Stage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Success_Stage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Success_Stage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Success_Stage(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jExit1;
    private javax.swing.JLabel jExit2;
    private javax.swing.JLabel jLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jPlayAgain1;
    private javax.swing.JLabel jPlayAgain2;
    private javax.swing.JLabel jScore1;
    private javax.swing.JLabel jScore2;
    private javax.swing.JLabel jSelamat;
    private javax.swing.JLabel jSkor;
    // End of variables declaration//GEN-END:variables
}
