/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tebak_Lagu;

import DBKon.koneksi;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class Failed_Stage extends javax.swing.JFrame {
koneksi kon;
int skor = 0;
static String username = Tebak_Lagu.MainMenu.username;
    /**
     * Creates new form Failed_Stage
     */
    public Failed_Stage(int skor) {
        initComponents();
        kon = new koneksi();
        this.skor = skor;
        jSelamat.setText(getUser());
        jSkor.setText(""+skor);
        try{
            String ubah = "update tebak_lagu set skor = '"+skor+"' where user = '"+getUser()+"'";
            Statement st = kon.con.createStatement();
            st.executeUpdate(ubah);
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }      
    }
        
    public static String getUser(){
        String temp2 = Tebak_Lagu.MainMenu.username;
        username = "";
        return temp2;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnAllScore = new javax.swing.JLabel();
        jbtnAllScore2 = new javax.swing.JLabel();
        jbtnExit = new javax.swing.JLabel();
        jbtnExit2 = new javax.swing.JLabel();
        jbtnPlayAgain = new javax.swing.JLabel();
        jbtnPlayAgain2 = new javax.swing.JLabel();
        jSelamat = new javax.swing.JLabel();
        jSkor = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnAllScore.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jbtnAllScore.setForeground(new java.awt.Color(255, 252, 232));
        jbtnAllScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbtnAllScore.setText("All Scores");
        jbtnAllScore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnAllScoreMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnAllScoreMouseEntered(evt);
            }
        });
        jPanel1.add(jbtnAllScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 466, 188, 30));

        jbtnAllScore2.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jbtnAllScore2.setForeground(new java.awt.Color(255, 153, 51));
        jbtnAllScore2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbtnAllScore2.setText("All Scores");
        jbtnAllScore2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnAllScore2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnAllScore2MouseExited(evt);
            }
        });
        jPanel1.add(jbtnAllScore2, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 466, 188, 30));

        jbtnExit.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jbtnExit.setForeground(new java.awt.Color(255, 252, 232));
        jbtnExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbtnExit.setText("EXIt");
        jbtnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnExitMouseEntered(evt);
            }
        });
        jPanel1.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 466, 188, 30));

        jbtnExit2.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jbtnExit2.setForeground(new java.awt.Color(255, 153, 51));
        jbtnExit2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbtnExit2.setText("EXIt");
        jbtnExit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnExit2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnExit2MouseExited(evt);
            }
        });
        jPanel1.add(jbtnExit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 466, 188, 30));

        jbtnPlayAgain.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jbtnPlayAgain.setForeground(new java.awt.Color(204, 51, 0));
        jbtnPlayAgain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbtnPlayAgain.setText("Play Again");
        jbtnPlayAgain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnPlayAgainMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnPlayAgainMouseEntered(evt);
            }
        });
        jPanel1.add(jbtnPlayAgain, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 466, 188, 30));

        jbtnPlayAgain2.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jbtnPlayAgain2.setForeground(new java.awt.Color(255, 153, 51));
        jbtnPlayAgain2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbtnPlayAgain2.setText("Play Again");
        jbtnPlayAgain2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnPlayAgain2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnPlayAgain2MouseExited(evt);
            }
        });
        jPanel1.add(jbtnPlayAgain2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 466, 188, 30));

        jSelamat.setFont(new java.awt.Font("Matura MT Script Capitals", 1, 24)); // NOI18N
        jSelamat.setForeground(new java.awt.Color(7, 3, 3));
        jSelamat.setMaximumSize(new java.awt.Dimension(450, 50));
        jPanel1.add(jSelamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 190, 50));

        jSkor.setFont(new java.awt.Font("Matura MT Script Capitals", 1, 48)); // NOI18N
        jSkor.setForeground(new java.awt.Color(7, 3, 3));
        jSkor.setMaximumSize(new java.awt.Dimension(450, 50));
        jPanel1.add(jSkor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 100, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tebak_Lagu/img/a46079da-1b58-4be4-8424-bd27648d5343.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAllScoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnAllScoreMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Peringkat(skor).setVisible(true);
    }//GEN-LAST:event_jbtnAllScoreMouseClicked

    private void jbtnAllScoreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnAllScoreMouseEntered
        // TODO add your handling code here:
        jbtnAllScore.setVisible(false);
        jbtnAllScore2.setVisible(true);
    }//GEN-LAST:event_jbtnAllScoreMouseEntered

    private void jbtnAllScore2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnAllScore2MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Peringkat(skor).setVisible(true);
    }//GEN-LAST:event_jbtnAllScore2MouseClicked

    private void jbtnAllScore2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnAllScore2MouseExited
        // TODO add your handling code here:
        jbtnAllScore2.setVisible(false);
        jbtnAllScore.setVisible(true);
    }//GEN-LAST:event_jbtnAllScore2MouseExited

    private void jbtnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnExitMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Menu.MainMenu().setVisible(true);
    }//GEN-LAST:event_jbtnExitMouseClicked

    private void jbtnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnExitMouseEntered
        // TODO add your handling code here:
        jbtnExit.setVisible(false);
        jbtnExit2.setVisible(true);
    }//GEN-LAST:event_jbtnExitMouseEntered

    private void jbtnExit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnExit2MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Menu.MainMenu().setVisible(true);
    }//GEN-LAST:event_jbtnExit2MouseClicked

    private void jbtnExit2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnExit2MouseExited
        // TODO add your handling code here:
        jbtnExit2.setVisible(false);
        jbtnExit.setVisible(true);
    }//GEN-LAST:event_jbtnExit2MouseExited

    private void jbtnPlayAgainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnPlayAgainMouseClicked
        // TODO add your handling code here:
        skor = 0;
        getUser();
        this.setVisible(false);
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_jbtnPlayAgainMouseClicked

    private void jbtnPlayAgainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnPlayAgainMouseEntered
        // TODO add your handling code here:
        jbtnPlayAgain.setVisible(false);
        jbtnPlayAgain2.setVisible(true);
    }//GEN-LAST:event_jbtnPlayAgainMouseEntered

    private void jbtnPlayAgain2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnPlayAgain2MouseClicked
        // TODO add your handling code here:
        skor = 0;
        getUser();
        this.setVisible(false);
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_jbtnPlayAgain2MouseClicked

    private void jbtnPlayAgain2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnPlayAgain2MouseExited
        // TODO add your handling code here:
        jbtnPlayAgain2.setVisible(false);
        jbtnPlayAgain.setVisible(true);
    }//GEN-LAST:event_jbtnPlayAgain2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Failed_Stage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Failed_Stage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Failed_Stage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Failed_Stage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Failed_Stage(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jSelamat;
    private javax.swing.JLabel jSkor;
    private javax.swing.JLabel jbtnAllScore;
    private javax.swing.JLabel jbtnAllScore2;
    private javax.swing.JLabel jbtnExit;
    private javax.swing.JLabel jbtnExit2;
    private javax.swing.JLabel jbtnPlayAgain;
    private javax.swing.JLabel jbtnPlayAgain2;
    // End of variables declaration//GEN-END:variables
}
