/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tebak_Lagu;

import DBKon.koneksi;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author USER
 */
public class Peringkat extends javax.swing.JFrame {
    koneksi kon;
    int skor = 0;

    /**
     * Creates new form Peringkat
     */
    public Peringkat(int skor) {
        kon = new koneksi();
        this.skor = skor;
        initComponents();
        
        Object header[] = {"USERNAME", "SKOR"};
        DefaultTableModel data = new DefaultTableModel(null, header);
        jTable1.setModel(data);
        String tampil = "select * from tebak_lagu order by skor DESC";
        try{
            Statement st = kon.con.createStatement();
            ResultSet rs = st.executeQuery(tampil);
            while(rs.next()){
                String kolom1 = rs.getString(1);
                String kolom2 = rs.getString(2);
                String kolom[] = {kolom1, kolom2};
                data.addRow(kolom);
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error : "+e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jCariUser = new javax.swing.JTextField();
        jbtnCari1 = new javax.swing.JLabel();
        jbtnCari2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N

        jTable1.setBackground(new java.awt.Color(255, 204, 102));
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(30);
        jTable1.setSelectionBackground(new java.awt.Color(255, 51, 0));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 660, 260));

        jCariUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCariUserActionPerformed(evt);
            }
        });
        jPanel1.add(jCariUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 530, 30));

        jbtnCari1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnCari1.setForeground(new java.awt.Color(255, 255, 255));
        jbtnCari1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbtnCari1.setText("CARI");
        jbtnCari1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnCari1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnCari1MouseEntered(evt);
            }
        });
        jPanel1.add(jbtnCari1, new org.netbeans.lib.awtextra.AbsoluteConstraints(673, 196, 105, 21));

        jbtnCari2.setBackground(new java.awt.Color(204, 204, 204));
        jbtnCari2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnCari2.setForeground(new java.awt.Color(255, 204, 102));
        jbtnCari2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbtnCari2.setText("CARI");
        jbtnCari2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnCari2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnCari2MouseExited(evt);
            }
        });
        jPanel1.add(jbtnCari2, new org.netbeans.lib.awtextra.AbsoluteConstraints(673, 196, 105, 21));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tebak_Kata/img/btnsearch.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, -1, 30));

        jLabel2.setText("Silahkan masukan username yang ingin dicari");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 153, 0));
        jButton1.setText("BACK");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(813, 553, 70, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tebak_Lagu/img/PeringkatTL.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCariUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCariUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCariUserActionPerformed

    private void jbtnCari1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnCari1MouseClicked
        // TODO add your handling code here:
        Object header[] = {"user", "skor"};
        DefaultTableModel data = new DefaultTableModel(null, header);
        jTable1.setModel(data);
        String tampil = "select * from tebak_lagu where user like '%"+jCariUser.getText()+"%'";
        try{
            Statement st = kon.con.createStatement();
            ResultSet rs = st.executeQuery(tampil);
            while(rs.next()){
                String kolom1 = rs.getString(1);
                String kolom2 = rs.getString(2);
                String kolom[] = {kolom1, kolom2};
                data.addRow(kolom);
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error : "+e.getMessage());
        }
    }//GEN-LAST:event_jbtnCari1MouseClicked

    private void jbtnCari1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnCari1MouseEntered
        // TODO add your handling code here:
        jbtnCari1.setVisible(false);
        jbtnCari2.setVisible(true);
    }//GEN-LAST:event_jbtnCari1MouseEntered

    private void jbtnCari2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnCari2MouseExited
        // TODO add your handling code here:
        jbtnCari2.setVisible(false);
        jbtnCari1.setVisible(true);
    }//GEN-LAST:event_jbtnCari2MouseExited

    private void jbtnCari2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnCari2MouseClicked
        // TODO add your handling code here:
        Object header[] = {"user", "skor"};
        DefaultTableModel data = new DefaultTableModel(null, header);
        jTable1.setModel(data);
        String tampil = "select * from tebak_lagu where user like '%"+jCariUser.getText()+"%'";
        try{
            Statement st = kon.con.createStatement();
            ResultSet rs = st.executeQuery(tampil);
            while(rs.next()){
                String kolom1 = rs.getString(1);
                String kolom2 = rs.getString(2);
                String kolom[] = {kolom1, kolom2};
                data.addRow(kolom);
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error : "+e.getMessage());
        }
    }//GEN-LAST:event_jbtnCari2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        if(skor == 100){
            new Success_Stage(skor).setVisible(true);
        } else{
            new Failed_Stage(skor).setVisible(true);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Peringkat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Peringkat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Peringkat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Peringkat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Peringkat(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jCariUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jbtnCari1;
    private javax.swing.JLabel jbtnCari2;
    // End of variables declaration//GEN-END:variables
}
