/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menu;

/**
 *
 * @author USER
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnTG1 = new javax.swing.JLabel();
        jbtnTG2 = new javax.swing.JLabel();
        jbtnTL1 = new javax.swing.JLabel();
        jbtnTL2 = new javax.swing.JLabel();
        jExit1 = new javax.swing.JLabel();
        jExit2 = new javax.swing.JLabel();
        jCredit1 = new javax.swing.JLabel();
        jCredit2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnTG1.setBackground(new java.awt.Color(255, 204, 153));
        jbtnTG1.setForeground(new java.awt.Color(255, 204, 153));
        jbtnTG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/TebakGambar.png"))); // NOI18N
        jbtnTG1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnTG1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnTG1MouseEntered(evt);
            }
        });
        jPanel1.add(jbtnTG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 160, 130));

        jbtnTG2.setBackground(new java.awt.Color(102, 102, 102));
        jbtnTG2.setForeground(new java.awt.Color(255, 204, 153));
        jbtnTG2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbtnTG2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/TebakGambar2.png"))); // NOI18N
        jbtnTG2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnTG2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnTG2MouseExited(evt);
            }
        });
        jPanel1.add(jbtnTG2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 160, 130));

        jbtnTL1.setBackground(new java.awt.Color(255, 204, 153));
        jbtnTL1.setForeground(new java.awt.Color(255, 204, 153));
        jbtnTL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/TebakLagu.png"))); // NOI18N
        jbtnTL1.setText("jLabel1");
        jbtnTL1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnTL1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnTL1MouseEntered(evt);
            }
        });
        jPanel1.add(jbtnTL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 160, 130));

        jbtnTL2.setBackground(new java.awt.Color(255, 204, 153));
        jbtnTL2.setForeground(new java.awt.Color(255, 204, 153));
        jbtnTL2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/TebakLagu2.png"))); // NOI18N
        jbtnTL2.setText("jLabel1");
        jbtnTL2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnTL2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnTL2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnTL2MouseExited(evt);
            }
        });
        jPanel1.add(jbtnTL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 160, 130));

        jExit1.setBackground(new java.awt.Color(248, 249, 232));
        jExit1.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jExit1.setForeground(new java.awt.Color(255, 255, 255));
        jExit1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jExit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/btnExit.png"))); // NOI18N
        jExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jExit1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jExit1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jExit1MouseExited(evt);
            }
        });
        jPanel1.add(jExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(611, 370, 150, 150));

        jExit2.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jExit2.setForeground(new java.awt.Color(255, 204, 0));
        jExit2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jExit2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/btnExit2.png"))); // NOI18N
        jExit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jExit2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jExit2MouseExited(evt);
            }
        });
        jPanel1.add(jExit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(611, 370, 150, 150));

        jCredit1.setBackground(new java.awt.Color(248, 249, 232));
        jCredit1.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jCredit1.setForeground(new java.awt.Color(255, 255, 255));
        jCredit1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCredit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/btnCredit.png"))); // NOI18N
        jCredit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCredit1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jCredit1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jCredit1MouseExited(evt);
            }
        });
        jPanel1.add(jCredit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 370, 150, 150));

        jCredit2.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jCredit2.setForeground(new java.awt.Color(255, 204, 0));
        jCredit2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCredit2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/btnCredit2.png"))); // NOI18N
        jCredit2.setPreferredSize(new java.awt.Dimension(188, 168));
        jCredit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCredit2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jCredit2MouseExited(evt);
            }
        });
        jPanel1.add(jCredit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 370, 150, 150));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/MainMenuu.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setPreferredSize(new java.awt.Dimension(900, 600));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnTG2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnTG2MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Tebak_Kata.MainMenu().setVisible(true);
    }//GEN-LAST:event_jbtnTG2MouseClicked

    private void jbtnTG2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnTG2MouseExited
        // TODO add your handling code here:
        jbtnTG1.setVisible(true);
        jbtnTG2.setVisible(false);
    }//GEN-LAST:event_jbtnTG2MouseExited

    private void jbtnTL1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnTL1MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Tebak_Lagu.MainMenu().setVisible(true);
    }//GEN-LAST:event_jbtnTL1MouseClicked

    private void jbtnTL1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnTL1MouseEntered
        // TODO add your handling code here:
        jbtnTL1.setVisible(false);
        jbtnTL2.setVisible(true);
    }//GEN-LAST:event_jbtnTL1MouseEntered

    private void jbtnTL2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnTL2MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Tebak_Lagu.MainMenu().setVisible(true);
    }//GEN-LAST:event_jbtnTL2MouseClicked

    private void jbtnTL2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnTL2MouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_jbtnTL2MouseEntered

    private void jbtnTL2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnTL2MouseExited
        // TODO add your handling code here:
        jbtnTL1.setVisible(true);
        jbtnTL2.setVisible(false);
    }//GEN-LAST:event_jbtnTL2MouseExited

    private void jCredit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCredit1MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new credit().setVisible(true);
    }//GEN-LAST:event_jCredit1MouseClicked

    private void jCredit1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCredit1MouseEntered
        // TODO add your handling code here:
        jCredit1.setVisible(false);
        jCredit2.setVisible(true);

    }//GEN-LAST:event_jCredit1MouseEntered

    private void jCredit1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCredit1MouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jCredit1MouseExited

    private void jCredit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCredit2MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new credit().setVisible(true);
    }//GEN-LAST:event_jCredit2MouseClicked

    private void jbtnTG1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnTG1MouseEntered
        // TODO add your handling code here:
        jbtnTG1.setVisible(false);
        jbtnTG2.setVisible(true);
    }//GEN-LAST:event_jbtnTG1MouseEntered

    private void jbtnTG1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnTG1MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Tebak_Kata.MainMenu().setVisible(true);
    }//GEN-LAST:event_jbtnTG1MouseClicked

    private void jExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExit1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jExit1MouseClicked

    private void jExit1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExit1MouseEntered
        // TODO add your handling code here:
        jExit1.setVisible(false);
        jExit2.setVisible(true);
    }//GEN-LAST:event_jExit1MouseEntered

    private void jExit1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExit1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jExit1MouseExited

    private void jExit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExit2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jExit2MouseClicked

    private void jExit2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExit2MouseExited
        // TODO add your handling code here:
        jExit2.setVisible(false);
        jExit1.setVisible(true);
    }//GEN-LAST:event_jExit2MouseExited

    private void jCredit2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCredit2MouseExited
        // TODO add your handling code here:
        jCredit1.setVisible(true);
        jCredit2.setVisible(false);
    }//GEN-LAST:event_jCredit2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jCredit1;
    private javax.swing.JLabel jCredit2;
    private javax.swing.JLabel jExit1;
    private javax.swing.JLabel jExit2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jbtnTG1;
    private javax.swing.JLabel jbtnTG2;
    private javax.swing.JLabel jbtnTL1;
    private javax.swing.JLabel jbtnTL2;
    // End of variables declaration//GEN-END:variables
}
